export { SceneCanvas } from './SceneCanvas';
export { SceneLoader } from './SceneLoader';
export { Lighting } from './Lighting';
export { Environment } from './Environment';
export { CameraController } from './CameraController';
export { OfficeModel, RoomsModel } from './OfficeModel';
export { ROOM_CONFIG } from './roomConfig';
export { StarParticles } from './StarParticles';
export { InteractiveObject } from './InteractiveObject';
export { DimmableRoom } from './DimmableRoom';
export { CameraDebugger } from './CameraDebugger';
export { Room1InteractiveObjects } from './room1';
export { Room2InteractiveObjects } from './room2';
export { Room3InteractiveObjects } from './room3';
export { Room6InteractiveObjects } from './room6';
